apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/rollingupdate-target: version-configmap
    app.ibm.com/is-local-deployable: "false"
  name: rollingupdate-configmap
  namespace: default
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: default
    data:
      purpose: for test
  placement:
    clusterSelector: {}
