apiVersion: multicloud-apps.io/v1alpha1
kind: Deployable
metadata:
  annotations:
    multicloud-apps.io/rollingupdate-target: version-configmap
    multicloud-apps.io/is-local-deployable: "false"
  name: rollingupdate-configmap
  namespace: default
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: default
    data:
      purpose: for test
  placement:
    clusterSelector: {}
