apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-deployable
  labels:
    name: multicloud-operators-deployable
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-deployable
  template:
    metadata:
      labels:
        name: multicloud-operators-deployable
    spec:
      serviceAccountName: multicloud-operators
      containers:
        - name: multicloud-operators-deployable
          # Replace this with the built image name
          image: quay.io/multicloudlab/multicloud-operators-deployable
          command:
          - multicloud-operators-deployable
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-deployable"
