apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: multicloud-operators
rules:
- apiGroups:
  - app.ibm.com
  resources:
  - placementrules
  verbs:
  - get
  - list
- apiGroups:
  - app.ibm.com
  resources:
  - deployables
  verbs:
  - '*'
- apiGroups:
  - clusterregistry.k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - create
- apiGroups:
  - multicloud-apps.io
  resources:
  - '*'
  - deployables
  verbs:
  - '*'
