kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators-deployable
subjects:
- kind: ServiceAccount
  name: multicloud-operators-deployable
roleRef:
  kind: Role
  name: multicloud-operators-deployable
  apiGroup: rbac.authorization.k8s.io
